language: go

go:
  # - 1.10.2 
  - 1.13
  # - tip

os:
  - linux
  # - osx
  
services:
  # - mysql

sudo: false

addons:
  apt:
    packages:
    - wget
  
env:
  matrix:
    # CODECOV_TOKEN only needed for private repos
    - DATASOURCE1=travis   SQL_PW=""    GO111MODULE=on   CODECOV_TOKEN="5223b84b-6a98-46c1-882e-0bf0307eef2b"

before_install:
  # codecov.io requirement:
  - go get -t -v ./...


install:
  # - go get -t ./...  

before_script:
  # - mysql -e 'create database exceldb_test;'
  # - go vet ./...

script:
  # - go test -v ./...
  # codecov.io replacement:
  - go test -race -coverprofile=coverage.txt -covermode=atomic

notifications:
  email: false

after_success:
  # codecov.io requirement:
  - bash <(curl -s https://codecov.io/bash)